---
# common vars
lab_domain: vsphere.lab

lab_id: "{{ present_lab_id|default(1) }}"
lab_padded_id: "{{ '%02d'|format(lab_id|int) }}"

esxi_mac_seed: "00:50:56:3F:{{ lab_padded_id }}:"

management_network_gateway: 172.16.100.1
global_mtu: 9000

default_lab_password: VMware1!

vlans:
  - vlan_id: 2001
    gateway_ip: 172.16.201.1
    mask: 24
    description: vMotion Network
  - vlan_id: 2002
    gateway_ip: 172.16.202.1
    mask: 24
    description: NFS Storage Network
  - vlan_id: 2003
    gateway_ip: 172.16.203.1
    mask: 24
    description: vSAN Network
  - vlan_id: 2004
    gateway_ip: 172.16.204.1
    mask: 24
    description: VLAN for App Network
  - vlan_id: 2005
    gateway_ip: 172.16.205.1
    mask: 24
    description: VLAN for Database Network
  - vlan_id: 2006
    gateway_ip: 172.16.206.1
    mask: 24
    description: VLAN for NSX-T Transport Node Overlay
  - vlan_id: 2007
    gateway_ip: 172.16.207.1
    mask: 24
    description: VLAN for NSX-T Edge Node Overlay
  - vlan_id: 2008
    gateway_ip: 172.16.208.1
    mask: 24
    description: VLAN for NSX-T Edge Node Left Uplink
  - vlan_id: 2009
    gateway_ip: 172.16.209.1
    mask: 24
    description: VLAN for NSX-T Edge Node Right Uplink

vyos_server:
  name: "vsphere-lab{{ lab_padded_id }}-vyos"
  num_cpus: 2
  memory_gb: 1
  provision_mac_address: "{{ esxi_mac_seed }}B1"
  external_mac_address: "{{ esxi_mac_seed }}B2"
  internal_mac_address: "{{ esxi_mac_seed }}B3"
  initial_powerstate: powered-on

vcenter_server:
  name: "vapp-vcenter7"
  hostname: vcenter
  ip: 172.16.100.30
  prefix: 24

infra_servers:
  - name: "vsphere-lab{{ lab_padded_id }}-dnsmasq"
    hostname: dnsmasq01
    ip: 172.16.100.11
    netmask: 255.255.255.0
    prefix: 24
    num_cpus: 2
    memory_gb: 1 
    disk: []
    initial_powerstate: powered-on
  - name: "vsphere-lab{{ lab_padded_id }}-nfsserver"
    hostname: nfsserver01
    ip: 172.16.100.12
    netmask: 255.255.255.0
    prefix: 24
    num_cpus: 2
    memory_gb: 2 
    disk:
      - size_gb: 20
        type: thin
      - size_gb: 500
        type: thin
    initial_powerstate: powered-on

rdp_servers:
  - name: "vsphere-lab{{ lab_padded_id }}-rdp"
    hostname: rdp01
    ip: 172.16.100.13
    netmask: 255.255.255.0
    prefix: 24
    num_cpus: 2
    memory_gb: 8
    disk: []
    initial_powerstate: powered-on

esxi_servers:
  - name: "vsphere-lab{{ lab_padded_id }}-esxi01"
    hostname: esxi01
    ip: 172.16.100.101
    netmask: 255.255.255.0
    mac_addresses: 
      - "{{ esxi_mac_seed }}01"
      - "{{ esxi_mac_seed }}A1"
    num_cpus: 4
    memory_gb: 16 
    initial_powerstate: powered-off
  - name: "vsphere-lab{{ lab_padded_id }}-esxi02"
    hostname: esxi02
    ip: 172.16.100.102
    netmask: 255.255.255.0
    mac_addresses: 
      - "{{ esxi_mac_seed }}02"
      - "{{ esxi_mac_seed }}A2"
    num_cpus: 4
    memory_gb: 16 
    initial_powerstate: powered-off
  - name: "vsphere-lab{{ lab_padded_id }}-esxi03"
    hostname: esxi03
    ip: 172.16.100.103
    netmask: 255.255.255.0
    mac_addresses: 
      - "{{ esxi_mac_seed }}03"
      - "{{ esxi_mac_seed }}A3"
    num_cpus: 4
    memory_gb: 16 
    initial_powerstate: powered-off
  - name: "vsphere-lab{{ lab_padded_id }}-esxi04"
    hostname: esxi04
    ip: 172.16.100.104
    netmask: 255.255.255.0
    mac_addresses: 
      - "{{ esxi_mac_seed }}04"
      - "{{ esxi_mac_seed }}A4"
    num_cpus: 4
    memory_gb: 16 
    initial_powerstate: powered-off
  - name: "vsphere-lab{{ lab_padded_id }}-esxi05"
    hostname: esxi05
    ip: 172.16.100.105
    netmask: 255.255.255.0
    mac_addresses: 
      - "{{ esxi_mac_seed }}05"
      - "{{ esxi_mac_seed }}A5"
    num_cpus: 4
    memory_gb: 16 
    initial_powerstate: powered-off

dns_servers:
  - 10.0.3.194
  - 10.0.3.148

ntp_servers:
  - 10.0.11.163
  - 10.0.11.164

nfs_server:
  ip: 172.16.202.12
  vlan: 2002
  prefix: 24
  netmask: 255.255.255.0
  name: nfs

  
nfs_exports:
  paths:
    - /srv/nfs/datastore01
    - /srv/nfs/datastore02
    - /srv/nfs/datastore03
    - /srv/nfs/datastore04
  datastores:
    - nfs_datastore01
    - nfs_datastore02
    - nfs_datastore03
    - nfs_datastore04
  export_size_gb: 100
  client_network: 172.16.202.0/24


pg_management_name: pgManagement