---
# common vars

# lab variables
lab_domain: vsphere.lab

lab_id: "{{ present_lab_id }}"
lab_padded_id: "{{ '%02d'|format(lab_id|int) }}"

esxi_mac_seed: "00:50:56:3E:{{ lab_padded_id }}:"

# password used throughout the lab
default_lab_password: VMware1!

# network variables
lab_subnet: 172.16.0.0/16
management_network_gateway: 172.16.100.1
global_mtu: 9000

dns_servers: "{{ dns_servers_list | default([]) }}"

ntp_servers: "{{ ntp_servers_list | default([]) }}"
  
vlans:
  - vlan_id: 2001
    gateway_ip: 172.16.201.1
    mask: 24
    description: vMotion Network
  - vlan_id: 2002
    gateway_ip: 172.16.202.1
    mask: 24
    description: NFS Storage Network
  - vlan_id: 2003
    gateway_ip: 172.16.203.1
    mask: 24
    description: iSCSI Network
  - vlan_id: 2004
    gateway_ip: 172.16.204.1
    mask: 24
    description: VLAN for Fault Tolerance
  - vlan_id: 2005
    gateway_ip: 172.16.205.1
    mask: 24
    description: VLAN for App Network
  - vlan_id: 2006
    gateway_ip: 172.16.206.1
    mask: 24
    description: VLAN for Database Network
  - vlan_id: 2007
    gateway_ip: 172.16.207.1
    mask: 24
    description: VLAN Available 01
  - vlan_id: 2008
    gateway_ip: 172.16.208.1
    mask: 24
    description: VLAN Available 02
  - vlan_id: 2009
    gateway_ip: 172.16.209.1
    mask: 24
    description: VLAN Available 03

vyos_dhcp_networks:
  - network: 172.16.205.0/24
    name: APP-NETWORK
    gateway: 172.16.205.1
    name_server: 172.16.100.11
    domain_name: "{{ lab_domain }}"
    range: 
      start: 172.16.205.100
      end: 172.16.205.199

  - network: 172.16.206.0/24
    name: DB-NETWORK
    gateway: 172.16.206.1
    name_server: 172.16.100.11
    domain_name: "{{ lab_domain }}"
    range: 
      start: 172.16.206.100
      end: 172.16.206.199

# lab virtual machines
vyos_server:
  name: "vsphere-lab{{ lab_padded_id }}-vyos"
  num_cpus: 2
  memory_gb: 1
  provision_mac_address: "{{ esxi_mac_seed }}F1"
  external_mac_address: "{{ esxi_mac_seed }}F2"
  internal_mac_address: "{{ esxi_mac_seed }}F3"
  initial_powerstate: powered-on

vcenter_server:
  name: "vapp-vcenter7"
  hostname: vcenter
  ip: 172.16.100.30
  prefix: 24
  nat_rules:
    - external_port: 31022
      internal_port: 22
      description: SSH to vcenter server
    - external_port: 443
      internal_port: 443
      description: HTTPS to vcenter server

# ATTENTION - do not change infra servers order
infra_servers:
  
  - name: "vsphere-lab{{ lab_padded_id }}-dnsmasq"
    hostname: dnsmasq01
    ip: 172.16.100.11
    netmask: 255.255.255.0
    prefix: 24
    num_cpus: 2
    memory_gb: 1 
    disk: []
    initial_powerstate: powered-on
    nat_rules:
      - external_port: 11022
        internal_port: 22
        description: SSH to dnsmasq01 server
  
  - name: "vsphere-lab{{ lab_padded_id }}-nfsserver"
    hostname: nfsserver01
    ip: 172.16.100.12
    netmask: 255.255.255.0
    prefix: 24
    num_cpus: 2
    memory_gb: 2 
    disk:
      - size_gb: 20
        type: thin
      - size_gb: 500
        type: thin
    initial_powerstate: powered-on
    nat_rules:
      - external_port: 12022
        internal_port: 22
        description: SSH to nfsserver01 server
  
  - name: "vsphere-lab{{ lab_padded_id }}-iscsiserver"
    hostname: iscsi01
    ip: 172.16.100.13
    netmask: 255.255.255.0
    prefix: 24
    num_cpus: 2
    memory_gb: 2 
    disk:
      - size_gb: 20
        type: thin
      - size_gb: 500
        type: thin
    initial_powerstate: powered-on
    nat_rules:
      - external_port: 13022
        internal_port: 22
        description: SSH to iscsi01 server

rdp_servers:
  - name: "vsphere-lab{{ lab_padded_id }}-rdp"
    hostname: rdp01
    ip: 172.16.100.21
    netmask: 255.255.255.0
    prefix: 24
    num_cpus: 2
    memory_gb: 8
    disk: []
    initial_powerstate: powered-on
    nat_rules:
      - external_port: 14022
        internal_port: 22
        description: SSH to rdp01 server
      - external_port: 3389
        internal_port: 3389
        description: RDP to rdp01 server
    
esxi_servers:

  - name: "vsphere-lab{{ lab_padded_id }}-esxi01"
    hostname: esxi01
    ip: 172.16.100.101
    netmask: 255.255.255.0
    mac_addresses: 
      - "{{ esxi_mac_seed }}01"
      - "{{ esxi_mac_seed }}A1"
    num_cpus: 4
    memory_gb: 16 
    initial_powerstate: powered-off
    nat_rules:
      - external_port: 21022
        internal_port: 22
        description: SSH to esxi01 server
      - external_port: 11443
        internal_port: 443
        description: HTTPS to esxi01 server

  - name: "vsphere-lab{{ lab_padded_id }}-esxi02"
    hostname: esxi02
    ip: 172.16.100.102
    netmask: 255.255.255.0
    mac_addresses: 
      - "{{ esxi_mac_seed }}02"
      - "{{ esxi_mac_seed }}A2"
    num_cpus: 4
    memory_gb: 16 
    initial_powerstate: powered-off
    nat_rules:
      - external_port: 22022
        internal_port: 22
        description: SSH to esxi02 server
      - external_port: 12443
        internal_port: 443
        description: HTTPS to esxi02 server

  - name: "vsphere-lab{{ lab_padded_id }}-esxi03"
    hostname: esxi03
    ip: 172.16.100.103
    netmask: 255.255.255.0
    mac_addresses: 
      - "{{ esxi_mac_seed }}03"
      - "{{ esxi_mac_seed }}A3"
    num_cpus: 4
    memory_gb: 16 
    initial_powerstate: powered-off
    nat_rules:
      - external_port: 23022
        internal_port: 22
        description: SSH to esxi03 server
      - external_port: 13443
        internal_port: 443
        description: HTTPS to esxi03 server

  - name: "vsphere-lab{{ lab_padded_id }}-esxi04"
    hostname: esxi04
    ip: 172.16.100.104
    netmask: 255.255.255.0
    mac_addresses: 
      - "{{ esxi_mac_seed }}04"
      - "{{ esxi_mac_seed }}A4"
    num_cpus: 4
    memory_gb: 16 
    initial_powerstate: powered-off
    nat_rules:
      - external_port: 24022
        internal_port: 22
        description: SSH to esxi04 server
      - external_port: 14443
        internal_port: 443
        description: HTTPS to esxi04 server

  - name: "vsphere-lab{{ lab_padded_id }}-esxi05"
    hostname: esxi05
    ip: 172.16.100.105
    netmask: 255.255.255.0
    mac_addresses: 
      - "{{ esxi_mac_seed }}05"
      - "{{ esxi_mac_seed }}A5"
    num_cpus: 4
    memory_gb: 16 
    initial_powerstate: powered-off
    nat_rules:
      - external_port: 25022
        internal_port: 22
        description: SSH to esxi05 server
      - external_port: 15443
        internal_port: 443
        description: HTTPS to esxi05 server

# nfs service
nfs_server:
  ip: 172.16.202.12
  vlan: 2002
  prefix: 24
  netmask: 255.255.255.0
  name: nfs

nfs_exports:
  paths:
    - /srv/nfs/datastore01
    - /srv/nfs/datastore02
    - /srv/nfs/datastore03
    - /srv/nfs/datastore04
  datastores:
    - nfs_datastore01
    - nfs_datastore02
    - nfs_datastore03
    - nfs_datastore04
  export_size_gb: 100
  client_network: 172.16.202.0/24

# iscsi service
iscsi_server:
  ip: 172.16.203.13
  vlan: 2003
  prefix: 24
  netmask: 255.255.255.0
  name: iscsi

iscsi_vols:
  size_gb: 100
  quantity: 4
  vg_name: vg_iscsi

#
# ESXi variables
#
# name of the local port group used for vCenter deployment
pg_management_name: pgManagement

# esxi root user
esxi_root: root

# local datastore prefix
local_datastore_prefix: local_

# esxi01 external ports
esxi01_https_port: 11443

#
# Windows variables
#
windows_administrator: administrator
windows_shell_type: cmd

#
# Linux variables
#
linux_root: root

#
# Vyos variables
#
vyos_connection: network_cli
vyos_network_os: vyos
vyos_user: vyos
vyos_password: laboratory
