---
# tasks file for roles/vsphere-lab-configure-esxi
- name: Gather info about vmhbas of an ESXi Host
  community.vmware.vmware_host_disk_info:
    hostname: '{{ external_ip }}'
    port: 11443
    username: 'root'
    password: 'VMware1!'
    validate_certs: "{{ validate_certs }}"
    esxi_hostname: 'esx01'
  delegate_to: localhost
  register: host_vmhbas

- name: Debug esxi devices
  debug: 
    msg: "{{ host_vmhbas }}"

- name: Mount VMFS datastores to ESXi
  community.vmware.vmware_host_datastore:
    hostname: '{{ external_ip }}'
    port: 11443
    username: 'root'
    password: 'VMware1!'
    datastore_name: 'esxi01_datastore01'
    datastore_type: '{{ item.type }}'
    vmfs_device_name: 'naa.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    vmfs_version: 6
    esxi_hostname: '{{ inventory_hostname }}'
    state: present
  delegate_to: localhost