---
# defaults file for roles/vsphere-lab-resources

lab_padded_id: "1"

# vcenter fqdn
vcenter_hostname: vcenter.local

# vcenter credentials
vcenter_credentials:
  username: administrator@vsphere.local
  password: VMware1!

# certs validation
validate_certs: false

# data center name
datacenter_name: LAB

# cluster name
cluster_name: LAB

# dpgs to provide conectivity for the lab
dpg_provision_name: dpgProvision
dpg_external_name: dpgExternal

# vlans default configurations
vlans:
  - vlan_id: 2001
    gateway_ip: 10.0.0.1
    mask: 24
    description: Any Network

# vyos server
vyos_server:
  name: vyos-vm
  num_cpus: 1
  memory_gb: 1
  provision_mac_address: INVALID
  external_mac_address: INVALID
  internal_mac_address: INVALID
  initial_powerstate: powered-on

# esxi servers
esxi_servers:
  - name: esxi-vm
    hostname: esxi-vm
    ip: 10.0.0.1
    netmask: 255.255.255.0
    mac_addresses:
      - INVALID
      - INVALID
    num_cpus: 1
    memory_gb: 1
    initial_powerstate: powered-off

# infra servers
infra_servers:
  - name: infra-vm
    hostname: infra-vm
    ip: 10.0.0.1
    netmask: 255.255.255.0
    prefix: 24
    num_cpus: 1
    memory_gb: 1
    disk: []
    initial_powerstate: powered-on

# rdp servers
rdp_servers:
  - name: rdp-vm
    hostname: rdp-vm
    ip: 10.0.0.1
    netmask: 255.255.255.0
    prefix: 24
    num_cpus: 1
    memory_gb: 1
    disk: []
    initial_powerstate: powered-on

# resource pool configurations
resource_pool:
  name: "RP-VSPHERELAB{{ lab_padded_id }}"
  memory:
    reservation: 8192
    limit: 81920
    shares: low
    expandable: false
  cpu:
    reservation: 2000
    limit: 20000
    shares: low
    expandable: false

# templates used
templates:
  infra_linux: Template-ol8rhk-lab
  vyos_vm: Template-vyos-13
  nested_esxi: Template-nestedesxi-7
  windows: Template-winserver19std
