---
#
# Creates basic infrastructure in vCenter
#
# Description:
#  - Creates Virtual Distributed Port Group for the laboratory 
#  - Creates Resource Pool
#  - Creates VM directories
#  - Creates VMs from templates

- name: Create basic infrastructure in vCenter
  hosts: vcenter
  connection: local
  gather_facts: true

  collections:
    - community.vmware

  pre_tasks:
    - include_vars:
        dir: credentials
        ignore_files: 
          - README.md

  roles:
    - roles/vsphere-lab-resources

  tasks:

    - name: Ensure VMs network is connected
      include_role: 
        name: roles/vsphere-lab-ensure-network-connected
      with_items: "{{ infra_servers + rdp_servers }}"
      vars: 
        vm_name: "{{ item.name }}"

#
# Configures inventory with vyos IP
#
- name: Configure vyos group in in-memory inventory
  hosts: localhost
  connection: local
  gather_facts: true

  tasks: 
    - name: Add vyos provision IP to inventory group
      add_host:
        name: "{{ vyos_provision_ip }}"
        groups: vyos  

#
# Configures vyos router
#
# Description:
#  - Configures vyos interfaces
#  - Configures vyos NAT rules

- name: Configure vyos router
  hosts: vyos
  gather_facts: false

  roles:
    - roles/vsphere-lab-vyos

#
# Configures infra servers
#

# bootstrap all servers
- name: Bootstrap infra servers
  hosts: infraserver
  gather_facts: true

  roles:
    - roles/vsphere-lab-infrabootstrap

# configures dnsmasq
- name: Configure dnsmasq
  hosts: dnsmasq
  gather_facts: true

  roles:
    - roles/vsphere-lab-dnsmasq

# configures nfs server VLAN
- name: provision nfs server VLAN
  hosts: nfsserver
  gather_facts: true

  roles:
    - roles/vsphere-lab-init-nfs-network

# configures dns in others servers
- name: Configures DNS in others infra servers
  hosts: dnsmasqclients
  gather_facts: true
  
  tasks: 
    - name: Remove old DNS from network interfaces
      lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{ network_vlan_interface }}"
        state: absent
        regexp: '^DNS'

  roles:
    - role: ahuffman.resolv
      resolv_nameservers: 
        - "{{ infra_servers.0.ip }}"
      resolv_domain: "{{ lab_domain }}"
      resolv_search:
        - "{{ lab_domain }}"

# configures nfs server and exports
- name: provision nfs server
  hosts: nfsserver
  gather_facts: true

  roles:
    - roles/vsphere-lab-init-nfs-vars
    - roles/vsphere-lab-init-nfs-fs
    - role: mrlesmithjr.nfs-server

#
# Kickstarts ESXi servers
#
- name: Kickstarts ESXi Servers
  hosts: vcenter
  connection: local
  gather_facts: true

  collections:
    - community.vmware

  pre_tasks:
    - include_vars:
        dir: credentials
        ignore_files: 
          - README.md

  roles:
    - roles/vsphere-lab-kickstart-esxi

#
# Configure ESXi for vCenter deployment
#
- name: Prepare esxi01 for vCenter installation
  hosts: localhost
  connection: local
  gather_facts: true

  collections:
    - community.vmware

  roles:
    - roles/vsphere-lab-prepare-esxi-for-vcenter

#
# Installs vCenter Server
#
- name: Deploy vcenter appliance
  hosts: deployvcenter
  gather_facts: true

  roles:
    - roles/vsphere-lab-deploy-vcenter

#
# Configures remote desktop
#
- name: Configure remote desktop
  hosts: remotedesktop
  gather_facts: false

  roles:
    - roles/vsphere-lab-prepare-remote-desktop