---
#
# Cleans all vSphere Lab infra
#
- name: Clean lab infra in vCenter
  hosts: vcenter
  connection: local
  gather_facts: true

  pre_tasks:

    - name: Include credentials
      ansible.builtin.include_vars:
        dir: credentials
        extensions: ['yml', 'yaml']
        ignore_unknown_extensions: true

  roles:
    - roles/vsphere-lab-destroy
