---
collections:
  - name: community.vmware
    version: 1.17.0

roles:
  - name: ahuffman.resolv
    version: 1.3.2

  - name: mrlesmithjr.nfs-server
    # version: 5.0.0

  - name: ondrejhome.targetcli
    version: 4.0.0
