---
# vars file for roles/vsphere-lab-dnsmasq
packages:
  - dnsmasq
  - nfs-utils

dhcp_range:
  start: 172.16.100.101
  end: "172.16.100.{{ 100 + (esxi_servers | length) }}"

dnsmasq_tftp_root_path: /srv/tftpboot
dnsmasq_tftp_path: "{{ dnsmasq_tftp_root_path }}/esxi7"
dnsmasq_nfs_root_path: /srv/nfs
dnsmasq_nfs_path: "{{ dnsmasq_nfs_root_path }}/esxi7"

dnsmasq_ks_kernelopt: "ks=nfs://{{ infra_servers.0.ip }}{{ dnsmasq_nfs_path }}/ks.cfg"
