---
# defaults file for roles/vsphere-lab-kickstart-esxi
vcenter_hostname: vcenter.local
vcenter_credentials:
  username: administrator@vsphere.local
  password: VMware1!

validate_certs: false

# timeouts and delays
vmware_guest_tools_wait_timeout: 1200
ansible_wait_for_delay: 30
ansible_wait_for_timeout: 1200

datacenter_name: LAB

external_ip: 127.0.0.1

esxi_servers:

  - name: "vsphere-lab{{ lab_padded_id }}-esxi01"
    nat_rules:
      - external_port: 11443
        internal_port: 443
        description: HTTPS to esxi01 server
