---
# vars file for roles/vsphere-lab-vyos
vyos_nat_rules:
  destination:
    - description: "Port Forward: SSH to DNSMASQ Server {{ infra_servers.0.ip }}"
      destination: 
        port: 22001
      inbound_interface: eth1
      protocol: tcp
      translation:
        address: "{{ infra_servers.0.ip }}"
        port: 22
    - description: "Port Forward: SSH to Remote Desktop Server {{ infra_servers.1.ip }}"
      destination: 
        port: 22002
      inbound_interface: eth1
      protocol: tcp
      translation:
        address: "{{ infra_servers.1.ip }}"
        port: 22
    - description: "Port Forward: SSH to NFS Server {{ infra_servers.2.ip }}"
      destination: 
        port: 22003
      inbound_interface: eth1
      protocol: tcp
      translation:
        address: "{{ infra_servers.2.ip }}"
        port: 22
  source:
    - description: "Masquerade internal Network"
      source:
        address: 172.16.0.0/16
      translation:
        address: masquerade
      outbound_interface: eth1