---

- name: Download esxi iso
  ansible.builtin.get_url:
    url: "{{ esxi_iso_url }}"
    dest: /tmp
    mode: '0644'
  when: esxi_iso_url
  register: esxi_iso

- name: Mount esxi iso
  ansible.posix.mount:
    src: "{{ esxi_iso.dest }}"
    path: /mnt
    opts: ro
    state: mounted
    fstype: iso9660

- name: Copy iso content to tftp root if necessary
  ansible.builtin.copy:
    src: /mnt/
    dest: "{{ dnsmasq_tftp_path }}"
    remote_src: true
    directory_mode: true

- name: Unmount esxi iso
  ansible.posix.mount:
    src: "{{ esxi_iso.dest }}"
    path: /mnt
    opts: ro
    state: unmounted
    fstype: iso9660

- name: Remove iso file
  ansible.builtin.file:
    path: "{{ esxi_iso.dest }}"
    state: absent
