---
- name: Download syslinux zip
  ansible.builtin.get_url:
    url: "{{ dnsmasq_syslinux_url }}"
    dest: /tmp
    mode: '0644'
  register: syslinux_zip

- name: Extract syslinux files
  ansible.builtin.unarchive:
    src: "{{ syslinux_zip.dest }}"
    dest: /tmp
    remote_src: true

- name: Copy pxelinux.0 file
  ansible.builtin.copy:
    src: /tmp/core/pxelinux.0
    dest: "{{ dnsmasq_tftp_path }}"
    remote_src: true

- name: Remove syslinux tmp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/core
    - "{{ syslinux_zip.dest }}"
