---
- name: Download syslinux zip
  get_url:
    url: "{{ dnsmasq_syslinux_url }}"
    dest: /tmp/syslinux.zip
    mode: '0644'

- name: Extract syslinux files
  unarchive:
    src: "/tmp/syslinux.zip"
    dest: /tmp
    remote_src: true

- name: Copy pxelinux.0 file
  copy:
    src: /tmp/core/pxelinux.0
    dest: "{{dnsmasq_tftp_path}}"
    remote_src: true

- name: Remove syslinux tmp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/core
    - /tmp/syslinux.zip