---
# defaults file for roles/vsphere-lab-vyos

lab_domain: vsphere.lab
route_networks: ['0.0.0.0/0']

external_ip: '10.0.0.1'
external_cidr: '8'

infra_servers:
  - ip: '172.16.1.1'
    nat_rules:
      - external_port: 11122
        internal_port: 22
        description: SSH for server infra

rdp_servers:
  - ip: '172.16.1.2'
    nat_rules:
      - external_port: 3389
        internal_port: 3389
        description: RDP for server rdp

vcenter_server:
  ip: '172.16.1.3'
  nat_rules:
    - external_port: 443
      internal_port: 443
      description: HTTPS for server vcenter

esxi_servers:
  - ip: '172.16.1.4'
    nat_rules:
      - external_port: 11443
        internal_port: 443
        description: HTTPS for server ESXi
