---
# defaults file for roles/vsphere-lab-prepare-remote-desktop
win_user_name: "labuser{{ lab_padded_id }}"
win_user_password: VMware1!

firefox_download_url: https://download.mozilla.org/?product=firefox-latest&os=win64&lang=en-US
putty_download_url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.76-installer.msi

tmp_directory: C:\Temp

#vmware_remote_console_zip_path: 

#ovf_template_windows_zip_path:
#ovf_template_linux_zip_path:

#iso_so_linux_path:
