---
# tasks file for roles/vsphere-lab-vyos

- name: Configures NAT Destination rules for servers
  ansible.builtin.set_fact:
    vyos_nat_destination_rules: "{{ vyos_nat_destination_rules + [nat_rule] }}"
  loop: "{{ (infra_servers + rdp_servers + esxi_servers) | subelements('nat_rules') }}"
  vars:
    nat_rule:
      description: "{{ item.1.description }}"
      destination:
        port: "{{ item.1.external_port }}"
      inbound_interface: eth1
      protocol: tcp
      translation:
        address: "{{ item.0.ip }}"
        port: "{{ item.1.internal_port }}"

- name: Configures NAT Destination rules for vCenter
  ansible.builtin.set_fact:
    vyos_nat_destination_rules: "{{ vyos_nat_destination_rules + [nat_rule] }}"
  loop: "{{ vcenter_server.nat_rules }}"
  vars:
    nat_rule:
      description: "{{ item.description }}"
      destination:
        port: "{{ item.external_port }}"
      inbound_interface: eth1
      protocol: tcp
      translation:
        address: "{{ vcenter_server.ip }}"
        port: "{{ item.internal_port }}"

- name: Configures NAT Destination rules for extra cases
  ansible.builtin.set_fact:
    vyos_nat_destination_rules: "{{ vyos_nat_destination_rules + [nat_rule] }}"
  loop: "{{ extra_destination_nat_rules }}"
  vars:
    nat_rule:
      description: "{{ item.description }}"
      destination:
        port: "{{ item.external_port }}"
      inbound_interface: eth1
      protocol: tcp
      translation:
        address: "{{ item.ip }}"
        port: "{{ item.internal_port }}"

- name: Wait for vyos to become reachable
  ansible.builtin.wait_for_connection:

- name: Set the hostname correctly
  vyos.vyos.vyos_config:
    lines:
      - set system host-name {{ vyos_fqdn }}

- name: Configure router interfaces
  vyos.vyos.vyos_interfaces:
    config:
      - name: "eth{{ idx }}"
        description: "{{ item.description }}"
        enabled: "{{ item.enabled }}"
        mtu: "{{ item.mtu }}"
    state: merged
  loop: "{{ vyos_interfaces }}"
  loop_control:
    index_var: idx

- name: Configure interfaces ip address
  vyos.vyos.vyos_l3_interfaces:
    config:
      - name: "eth{{ idx }}"
        ipv4: "{{ item.ipv4 }}"
    state: merged
  loop: "{{ vyos_interfaces }}"
  loop_control:
    index_var: idx

- name: Configure VLANs
  vyos.vyos.vyos_vlan:
    vlan_id: "{{ item.vlan_id }}"
    name: "\"{{ item.description }}\""
    interfaces: "{{ vyos_vlan_interface }}"
    state: present
  with_items: "{{ vlans }}"

- name: Configure VLANs IP address
  vyos.vyos.vyos_config:
    lines:
      - "set interfaces ethernet {{ vyos_vlan_interface }} vif {{ item.vlan_id }} address {{ item.gateway_ip }}/{{ item.mask }}"
  with_items: "{{ vlans }}"

- name: Configure external static routes
  vyos.vyos.vyos_static_routes:
    config:
      - address_families:
          - afi: ipv4
            routes:
              - dest: "{{ item }}"
                next_hops:
                  - forward_router_address: "{{ external_gateway }}"
    state: merged
  with_items: "{{ vyos_external_networks }}"

- name: Configure nat destination rules
  vyos.vyos.vyos_config:
    lines:
      - "set nat destination rule {{ idx + 1 }} description \"{{ item.description }}\""
      - "set nat destination rule {{ idx + 1 }} protocol {{ item.protocol }}"
      - "set nat destination rule {{ idx + 1 }} inbound-interface {{ item.inbound_interface }}"
      - "set nat destination rule {{ idx + 1 }} destination port {{ item.destination.port }}"
      - "set nat destination rule {{ idx + 1 }} translation address {{ item.translation.address }}"
      - "set nat destination rule {{ idx + 1 }} translation port {{ item.translation.port }}"
  loop: "{{ vyos_nat_destination_rules }} "
  loop_control:
    index_var: idx

- name: Configure nat source rules
  vyos.vyos.vyos_config:
    lines:
      - "set nat source rule {{ idx + 1 }} description \"{{ item.description }}\""
      - "set nat source rule {{ idx + 1 }} outbound-interface {{ item.outbound_interface }}"
      - "set nat source rule {{ idx + 1 }} source address {{ item.source.address }}"
      - "set nat source rule {{ idx + 1 }} translation address {{ item.translation.address }}"
  loop: "{{ vyos_nat_source_rules }}"
  loop_control:
    index_var: idx

- name: Configure dhcp server
  vyos.vyos.vyos_config:
    lines:
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} default-router {{ item.gateway }}"
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} dns-server {{ item.name_server }}"
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} domain-name {{ item.domain_name }}"
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} range 0 start {{ item.range.start }}"
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} range 0 stop {{ item.range.end }}"
  with_items: "{{ vyos_dhcp_networks }}"

- name: Save configurations
  vyos.vyos.vyos_config:
    save: "{{ vyos_save_configuration }}"
