---
- name: Boots ESXi {{ esxi_server.name }}
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_credentials.username }}"
    password: "{{ vcenter_credentials.password }}"
    validate_certs: "{{ validate_certs }}"
    folder: "{{ lab_full_path }}"
    name: "{{ esxi_server.name }}"
    state: "{{ esxi_powerstate }}"
  delegate_to: localhost

- name: Wait for VMware tools to become available in {{ esxi_server.name }}
  community.vmware.vmware_guest_tools_wait:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_credentials.username }}"
    password: "{{ vcenter_credentials.password }}"
    validate_certs: "{{ validate_certs }}"
    folder: "{{ lab_full_path }}"
    name: "{{ esxi_server.name }}"
    datacenter: "{{ datacenter_name }}"
    timeout: "{{ vmware_guest_tools_wait_timeout }}"
  delegate_to: localhost

- name: Waits for port 443 of esxi to be available - {{ esxi_server.name }}
  ansible.builtin.wait_for:
    host: "{{ external_ip }}"
    port: "{{ item.external_port }}"
    delay: "{{ ansible_wait_for_delay }}"
    timeout: "{{ ansible_wait_for_timeout }}"
    state: started
  loop: "{{ esxi_server.nat_rules }}"
  when: item.internal_port == 443
