---
# tasks file for roles/vsphere-lab-kickstart-esxi
- name: Kickstart ESXis
  ansible.builtin.include_tasks: kickstart-esxi.yml
  loop: "{{ esxi_servers }}"
  loop_control:
    loop_var: esxi_server
