---
# defaults file for roles/vsphere-lab-destroy
vcenter_hostname: vcenter.local

vcenter_credentials:
  username: administrator@vsphere.local
  password: VMware1!

validate_certs: false

datacenter_name: LAB
cluster_name: LAB
