---
# tasks file for roles/vsphere-lab-init-iscsi-network
- name: Ensure services are started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ network_services }}"

- name: Adjust virtual interface MTU
  community.general.nmcli:
    type: ethernet
    conn_name: "conn-{{ network_vlan_interface }}"
    ifname: "{{ network_vlan_interface }}"
    mtu: "{{ global_mtu }}"
    ip4: "{{ iscsi_server_ip }}/{{ iscsi_server_prefix }}"
    gw4: "{{ management_network_gateway }}"
    state: present

- name: Create ISCSI VLAN interface
  community.general.nmcli:
    type: vlan
    conn_name: "conn-{{ network_vlan_interface }}.{{ iscsi_server_service_vlan }}"
    vlanid: "{{ iscsi_server_service_vlan }}"
    vlandev: "{{ network_vlan_interface }}"
    ifname: "{{ network_vlan_interface }}.{{ iscsi_server_service_vlan }}"
    mtu: "{{ global_mtu }}"
    ip4: "{{ iscsi_server_service_ip }}/{{ iscsi_server_service_prefix }}"
    state: present
