---
# tasks file for roles/vsphere-lab-init-iscsi-network
- name: Ensure services are started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ network_services }}"

- name: Adjust virtual interface MTU
  nmcli:
    type: ethernet
    conn_name: "conn-{{ network_vlan_interface }}"
    ifname: "{{ network_vlan_interface }}"
    mtu: "{{ global_mtu }}"
    ip4: "{{ infra_servers.2.ip }}/{{ infra_servers.2.prefix }}"
    gw4: "{{ management_network_gateway }}"
    state: present

- name: Create ISCSI VLAN interface
  nmcli:
    type: vlan
    conn_name: "conn-{{ network_vlan_interface }}.{{ iscsi_server.vlan }}"
    vlanid: "{{ iscsi_server.vlan }}"
    vlandev: "{{ network_vlan_interface }}"
    ifname: "{{ network_vlan_interface }}.{{ iscsi_server.vlan }}"
    mtu: "{{ global_mtu }}"
    ip4: "{{ iscsi_server.ip }}/{{ iscsi_server.prefix }}"
    state: present