---

#
# Kickstarts ESXi servers
#
- name: Kickstarts ESXi Servers
  hosts: vcenter
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Include credentials
      ansible.builtin.include_vars:
        dir: ../credentials
        extensions: ['yml', 'yaml']
        ignore_unknown_extensions: true
      tags: [kickstart-esxi]

  roles:
    - role: ../roles/vsphere-lab-kickstart-esxi
      tags: [kickstart-esxi]

#
# Configure ESXi for vCenter deployment
#
- name: Prepare esxi01 for vCenter installation
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:

    - name: Set target esxi variables
      ansible.builtin.set_fact:
        esxi_hostname: "{{ esxi_servers.0.hostname }}"
        esxi_https_port: "{{ item.external_port }}"
      loop: "{{ esxi_servers.0.nat_rules }}"
      when: item.internal_port == 443
      tags: [prepare-esxi]

  roles:
    - role: ../roles/vsphere-lab-prepare-esxi-for-vcenter
      tags: [prepare-esxi]

#
# Installs vCenter Server
#
- name: Deploy vcenter appliance
  hosts: deployvcenter
  gather_facts: true

  pre_tasks:

    - name: Set vcenter install variables
      ansible.builtin.set_fact:
        esxi_hostname: "{{ esxi_servers.0.hostname }}"
        lab_dns_servers: "{{ [infra_servers.0.ip] }}"
        lab_ntp_servers: "{{ [infra_servers.0.ip] }}"
      tags: [deploy-vcenter]

  roles:
    - role: ../roles/vsphere-lab-deploy-vcenter
      tags: [deploy-vcenter]

#
# Assemble esxihosts group
#
- name: Assemble esxihosts group
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Add ESXi Hosts to inventory group
      ansible.builtin.add_host:
        hostname: "{{ item.0.hostname }}"
        ansible_host: "{{ external_ip }}"
        ansible_port: "{{ item.1.external_port }}"
        groups: esxihosts
      loop: "{{ esxi_servers | subelements('nat_rules') }}"
      when: item.1.internal_port == 22
      tags: [allow-legacy-cpu]

#
# Allow Legacy CPU configuration in ESXi servers
#
- name: Allow legacy CPU in ESXi servers
  hosts: esxihosts
  gather_facts: true

  roles:
    - role: ../roles/vsphere-lab-esxi-legacy-cpu
      tags: [allow-legacy-cpu]
