---
# deploys vcenter

# copy vcsa iso
  - name: VCSA Installation block
    block: 
      - name: Upload vcsa iso to server
        copy:
          src: "{{ vcsa_iso_path }}"
          dest: "/tmp"
        register: vcsa_iso

      - name: Mount vcsa iso
        mount:
          src: "{{ vcsa_iso.dest }}"
          path: /mnt
          opts: ro
          state: mounted
          fstype: iso9660

      - name: Place installation template
        template: 
          src: embedded_vCSA_on_ESXi.json.j2
          dest: /tmp/embedded_vCSA_on_ESXi.json
          mode: 0644

      - name: Deploy vcsa appliance
        shell: /mnt/vcsa-cli-installer/lin64/vcsa-deploy install --accept-eula --no-ssl-certificate-verification /tmp/embedded_vCSA_on_ESXi.json > /dev/null 2>&1
    
    always: 
      - name: Unmount vcsa iso
        mount:
          src: "{{ vcsa_iso.dest }}"
          path: /mnt
          opts: ro
          state: unmounted
          fstype: iso9660

      - name: Remove vcsa iso file
        file: 
          path: "{{ vcsa_iso.dest }}"
          state: absent