---
# tasks file for roles/vsphere-lab-deploy-vcenter

# install ovftool
- name: Check if ovftool is installed
  ansible.builtin.shell:
    cmd: command -v ovftool >/dev/null 2>&1
  register: ovftool_installed
  ignore_errors: true

- name: Install ovftool
  ansible.builtin.include_tasks: install-ovftool.yml
  when: ovftool_installed.rc == 1

# deploy vcenter
- name: Check if vcenter was deployed
  ansible.builtin.shell:
    cmd: "ovftool --noSSLVerify vi://root:'{{ default_lab_password }}'@{{ esxi_hostname }} | grep vcenter > /dev/null 2>&1"
  register: vcenter_deployed
  ignore_errors: true

- name: Deploy vcenter
  ansible.builtin.include_tasks: deploy-vcenter.yml
  when: vcenter_deployed.rc == 1
