---
# defaults file for roles/vsphere-lab-dnsmasq
dns_servers:
  - 8.8.8.8
  - 8.8.4.4

# URL for downloading syslinux
dnsmasq_syslinux_url: "https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/3.xx/syslinux-3.86.zip"

# URL for downloading ESXi ISO
esxi_iso_url: "http://127.0.0.1/"

# lab domain
lab_domain: vsphere.lab

# servers info needed
infra_servers:
  - hostname: dnsmasq01
    ip: 127.0.1.1

rdp_servers:
  - hostname: rdp01
    ip: 127.0.2.1

esxi_servers:
  - hostname: esxi01
    ip: 127.0.3.1
    mac_addresses:
      - INVALID

vcenter_server:
  hostname: vcenter
  ip: 127.0.4.1

nfs_server:
  hostname: nfs
  ip: 127.0.5.1

iscsi_server:
  hostname: iscsi
  ip: 127.0.6.1

# management network gateway
management_network_gateway: 127.0.0.1

# allow legacy CPU
allow_legacy_cpu: false
