---
# creates necessary infrastructure and the virtual machines
- name: Create Lab Virtual Distributed Switch
  community.vmware.vmware_dvswitch:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_credentials.username }}"
    password: "{{ vcenter_credentials.password }}"
    validate_certs: "{{ validate_certs }}"
    folder: "{{ lab_network_folder_full_path }}"
    switch_name: "{{ vds_name }}"
    switch_version: "{{ vds_version }}"
    mtu: "{{ vds_mtu }}"
    uplink_quantity: "{{ vds_uplink_quantity }}"
    state: "present"
  delegate_to: localhost

- name: Create Lab distributed port group
  community.vmware.vmware_dvs_portgroup:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_credentials.username }}"
    password: "{{ vcenter_credentials.password }}"
    validate_certs: "{{ validate_certs }}"
    portgroup_name: "{{ vds_dpg_name }}"
    switch_name: "{{ vds_name }}"
    vlan_id: "0,{{ vlan_ranges }}"
    vlan_trunk: true
    num_ports: 120
    port_binding: static
    network_policy:
      promiscuous: true
      forged_transmits: true
      mac_changes: true
    state: present
  delegate_to: localhost

- name: Gather cluster info - {{ cluster_name }}
  community.vmware.vmware_cluster_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_credentials.username }}"
    password: "{{ vcenter_credentials.password }}"
    validate_certs: "{{ validate_certs }}"
    cluster_name: "{{ cluster_name }}"
  delegate_to: localhost
  register: cluster_info

- name: Add each cluster host to vDS with no uplinks - {{ vds_name }}
  community.vmware.vmware_dvs_host:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_credentials.username }}"
    password: "{{ vcenter_credentials.password }}"
    validate_certs: "{{ validate_certs }}"
    esxi_hostname: "{{ item.name }}"
    switch_name: "{{ vds_name }}"
    state: present
  with_items: "{{ cluster_info.clusters[cluster_name].hosts }}"
  delegate_to: localhost

- name: Add lab resource pool to vCenter
  community.vmware.vmware_resource_pool:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_credentials.username }}'
    password: '{{ vcenter_credentials.password }}'
    validate_certs: "{{ validate_certs }}"
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    resource_pool: "{{ resource_pool.name }}"
    mem_shares: "{{ resource_pool.memory.shares }}"
    mem_limit: "{{ resource_pool.memory.limit }}"
    mem_reservation: "{{ resource_pool.memory.reservation }}"
    mem_expandable_reservations: "{{ resource_pool.memory.expandable }}"
    cpu_shares: "{{ resource_pool.cpu.shares }}"
    cpu_limit: "{{ resource_pool.cpu.limit }}"
    cpu_reservation: "{{ resource_pool.cpu.reservation }}"
    cpu_expandable_reservations: "{{ resource_pool.cpu.expandable }}"
    state: present
  delegate_to: localhost

- name: Creates infra virtual machines
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_credentials.username }}'
    password: '{{ vcenter_credentials.password }}'
    validate_certs: "{{ validate_certs }}"
    datacenter: "{{ datacenter_name }}"
    state: present
    folder: "{{ lab_vm_folder_full_path }}"
    template: "{{ templates.infra_linux }}"
    name: "{{ item.name }}"
    cluster: "{{ cluster_name }}"
    resource_pool: "{{ resource_pool.name }}"
    datastore: "{{ datastore_name }}"
    disk: "{{ item.disk }}"
    hardware:
      num_cpus: "{{ item.num_cpus }}"
      memory_mb: "{{ item.memory_gb * 1024 }}"
    networks:
      - name: "{{ vds_dpg_name }}"
        ip: "{{ item.ip }}"
        netmask: "{{ item.netmask }}"
        gateway: "{{ management_network_gateway }}"
    wait_for_ip_address: true
    wait_for_ip_address_timeout: 600
    customization:
      dns_servers: "{{ dns_servers }}"
      hostname: "{{ item.hostname }}"
  delegate_to: localhost
  with_items: "{{ infra_servers }}"
  when: item.name not in created_vms

- name: Creates rdp virtual machines
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_credentials.username }}'
    password: '{{ vcenter_credentials.password }}'
    validate_certs: "{{ validate_certs }}"
    datacenter: "{{ datacenter_name }}"
    state: present
    folder: "{{ lab_vm_folder_full_path }}"
    template: "{{ templates.windows }}"
    name: "{{ item.name }}"
    cluster: "{{ cluster_name }}"
    resource_pool: "{{ resource_pool.name }}"
    datastore: "{{ datastore_name }}"
    disk: "{{ item.disk }}"
    hardware:
      num_cpus: "{{ item.num_cpus }}"
      memory_mb: "{{ item.memory_gb * 1024 }}"
    networks:
      - name: "{{ vds_dpg_name }}"
        ip: "{{ item.ip }}"
        netmask: "{{ item.netmask }}"
        gateway: "{{ management_network_gateway }}"
        dns_servers: "{{ infra_servers.0.ip }}"
        domain: "{{ lab_domain }}"
        connected: true
        start_connected: true
    wait_for_ip_address: true
    wait_for_ip_address_timeout: 600
    customization:
      hostname: "{{ item.hostname }}"
      password: "{{ default_lab_password }}"
  delegate_to: localhost
  with_items: "{{ rdp_servers }}"
  when: item.name not in created_vms

# no network will be created to avoid customization problems
- name: Creates nested esxi virtual machines
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_credentials.username }}'
    password: '{{ vcenter_credentials.password }}'
    validate_certs: "{{ validate_certs }}"
    datacenter: "{{ datacenter_name }}"
    state: poweredoff
    folder: "{{ lab_vm_folder_full_path }}"
    template: "{{ templates.nested_esxi }}"
    name: "{{ item.name }}"
    cluster: "{{ cluster_name }}"
    resource_pool: "{{ resource_pool.name }}"
    datastore: "{{ datastore_name }}"
    disk: "{{ esxi_disks }}"
    hardware:
      num_cpus: "{{ item.num_cpus }}"
      num_cpu_cores_per_socket: "{{ item.num_cpus }}" # one license per ESXi
      memory_mb: "{{ item.memory_gb * 1024 }}"
  delegate_to: localhost
  with_items: "{{ esxi_servers }}"
  when: item.name not in created_vms

- name: Creates nested esxi network adapters with predefined mac address
  community.vmware.vmware_guest_network:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_credentials.username }}'
    password: '{{ vcenter_credentials.password }}'
    validate_certs: "{{ validate_certs }}"
    datacenter: "{{ datacenter_name }}"
    name: "{{ item.0.name }}"
    mac_address: "{{ item.1 }}"
    network_name: "{{ vds_dpg_name }}"
  delegate_to: localhost
  with_subelements:
    - "{{ esxi_servers }}"
    - "mac_addresses"
  when: item.0.name not in created_vms

# no network will be created to avoid customization problems
- name: Creates vyos virtual machine
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_credentials.username }}'
    password: '{{ vcenter_credentials.password }}'
    validate_certs: "{{ validate_certs }}"
    datacenter: "{{ datacenter_name }}"
    state: poweredoff
    folder: "{{ lab_vm_folder_full_path }}"
    template: "{{ templates.vyos_vm }}"
    name: "{{ vyos_server.name }}"
    cluster: "{{ cluster_name }}"
    resource_pool: "{{ resource_pool.name }}"
    datastore: "{{ datastore_name }}"
    hardware:
      num_cpus: "{{ vyos_server.num_cpus }}"
      memory_mb: "{{ vyos_server.memory_gb * 1024 }}"
  delegate_to: localhost
  when: vyos_server.name not in created_vms

- name: Creates vyos virtual machine network interfaces
  community.vmware.vmware_guest_network:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_credentials.username }}'
    password: '{{ vcenter_credentials.password }}'
    validate_certs: "{{ validate_certs }}"
    datacenter: "{{ datacenter_name }}"
    name: "{{ vyos_server.name }}"
    mac_address: "{{ item.mac }}"
    network_name: "{{ item.network_name }}"
  delegate_to: localhost
  with_items:
    - mac: "{{ vyos_server.provision_mac_address }}"
      network_name: "{{ dpg_provision_name }}"
    - mac: "{{ vyos_server.external_mac_address }}"
      network_name: "{{ dpg_external_name }}"
    - mac: "{{ vyos_server.internal_mac_address }}"
      network_name: "{{ vds_dpg_name }}"
  when: vyos_server.name not in created_vms

- name: Join all VMs in same ESXi - affinity rule
  community.vmware.vmware_vm_vm_drs_rule:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_credentials.username }}"
    password: "{{ vcenter_credentials.password }}"
    validate_certs: "{{ validate_certs }}"
    cluster_name: "{{ cluster_name }}"
    vms: "{{ to_be_created_vms }}"
    drs_rule_name: "{{ drs_affinity_rule }}"
    enabled: true
    mandatory: true
    affinity_rule: true
    state: present
  delegate_to: localhost
